name: README Badges
on:    
  workflow_dispatch:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # sed -Ei "s/(https:\/\/img\.shields\.io\/badge\/Lines_of_PHP-)[0-9]+(-blue)/
      #             https:\/\/img\.shields\.io\/badge\/Lines_of_PHP-$(
      # cat $(find * -iregex ".*\.php" | grep -v "countriesList") | sed "/^\s*#/d;/^\s*$/d" | wc -l
      # )-blue/g" README.md
      
      # sed -Ei "s/(https:\/\/img\.shields\.io\/badge\/Total_Lines_of_Code-)[0-9]+(-blue)/
      #             https:\/\/img\.shields\.io\/badge\/Total_Lines_of_Code-$(
      # cat $(find * -regextype posix-awk -iregex ".*\.(css|js|sql|php)"
      #     | grep -v "countriesList\|fontawesome") | sed "/^\s*#/d;/^\s*$/d" | wc -l
      # )-blue/g" README.md

      - name: Lines of Code Badges
        run: bash -c 'sed -Ei "s/(https:\/\/img\.shields\.io\/badge\/Lines_of_PHP-)[0-9]+(-blue)/https:\/\/img\.shields\.io\/badge\/Lines_of_PHP-$(cat $(find * -iregex ".*\.php" | grep -v "countriesList") | sed "/^\s*#/d;/^\s*$/d" | wc -l)-blue/g" README.md; sed -Ei "s/(https:\/\/img\.shields\.io\/badge\/Total_Lines_of_Code-)[0-9]+(-blue)/https:\/\/img\.shields\.io\/badge\/Total_Lines_of_Code-$(cat $(find * -regextype posix-awk -iregex ".*\.(css|js|sql|php)" | grep -v "countriesList\|fontawesome") | sed "/^\s*#/d;/^\s*$/d" | wc -l)-blue/g" README.md'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
